spring:
  datasource:
    url: jdbc:mysql://localhost:3307/index_lab?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: index_user
    password: index_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug